apiVersion: v1
kind: Service
metadata:
  name: cephfs-nginx
  namespace: playground
  labels:
    app: nginx
    type: web-servers
spec:
  ports:
    - name: cephfs-nginx
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30210
  selector:
    app: nginx
    type: web-servers
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-nginx
  namespace: playground
  labels:
    app: nginx
spec:
  storageClassName: rook-ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-nginx
  namespace: playground
  labels:
    app: nginx
    type: web-servers
spec:
  selector:
    matchLabels:
      app: nginx
      type: web-servers
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        type: web-servers
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              name: cephfs-nginx
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: cephfs-nginx
