apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: playground
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          rewrite .* http://linkedin.devorkin.net permanent;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: playground
  labels:
    app: nginx
    type: web-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      type: web-servers
  template:
    metadata:
      labels:
        type: web-servers
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: playground
spec:
  ports:
  - name: http
    nodePort: 30202
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: web-servers
  type: NodePort
