apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-ceph-object-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    sslCertificateRef:
    port: 80
    instances: 2
  healthCheck:
    readinessProbe:
      disabled: false
      failureThreshold: 2
      periodSeconds: 5
    startupProbe:
      disabled: false
