apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-audit-pv
  labels:
    type: local
spec:
  storageClassName: vault-audit-storage
  claimRef:
    name: audit-vault-0
    namespace: playground
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/vault/audit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-pv
  labels:
    type: local
spec:
  storageClassName: vault-data-storage
  claimRef:
    name: data-vault-0
    namespace: playground
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/vault/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
